import os
import re
import sys
import numpy as np
import pandas as pd

annot_file = sys.argv[1]
peak_file = sys.argv[2]
mark = sys.argv[3]

'''
annot_file = "H3K4me3.diff.peaks.annot" # this file is generated by annotatePeaks.pl 
PeakID (cmd=annotatePeaks.pl H3K4me3.diff.peaks CF_012559485.2.selected.fa -gtf GCF_012559485.2_MFA1912RKSv2.ncbiRefSeq.gtf)  Chr Start   End Strand  Peak Score  Focus Ratio/Region Size Annotation  Detailed Annotation Distance to TSS Nearest PromoterID  Entrez ID   Nearest Unigene Nearest Refseq  Nearest Ensembl Gene Name   Gene Alias  Gene Description    Gene Type
H3K4me3_peak_8206   NC_052266.1 101010402   101011500   +   5.13    NA  Intergenic  Intergenic  -89003  LOC123567948    LOC123567948    LOC123567948            LOC123567948            NA

peak_file = "H3K4me3.peak" # this file is generated by diffReps
Chrom   Start   End Length  Treatment.cnt   Control.cnt Treatment.avg   Control.avg Treatment.enr   Control.enr Event   log2FC  pval    padj    winSta  winEnd  winFC   winP    winQ
NC_012670.1 2901    4300    1400    209.79;216.06   503.73;281.32   212.92  392.52  0.04    0.04    Down    -0.88   1.30196972326233e-06    9.6902082995201e-06 3001    4000    -0.95   6.02781826148787e-07    3.19065586913864e-06
NC_012670.1 8101    9200    1100    208.72;186.10   495.11;169.03   197.41  332.07  0.06    0.05    Down    -0.75   2.0083936752358e-06 1.40196258809959e-05    8101    9100    -0.68   4.52090730479846e-06    2.05739764114375e-05

mark = "H3K4me3"
'''

padj_threshold = 0.01
log2FC_threshold = 1

print(f"Processing {peak_file} {annot_file} ...")

df = pd.read_csv(peak_file, sep="\t", comment="#")
df['PeakID'] = df.index.to_series().apply(lambda x: f"{mark}_peak_{x + 1}")
peak = df[["PeakID", "Event", "padj", "log2FC"]]
peak["log2FC_abs"] = peak["log2FC"].apply(lambda x: np.abs(x))
print(peak.shape)
peak.loc[(peak["padj"] > padj_threshold) | (peak["log2FC_abs"] < log2FC_threshold), "Event"] = "Unchange"
peak.loc[peak["Event"] == "Up", "Event"] = "Gain"
peak.loc[peak["Event"] == "Down", "Event"] = "Loss"

annot = pd.read_csv(annot_file, sep="\t")
cols = ['PeakID'] + list(annot.columns)[1:]
annot.columns = cols
annot = annot[["PeakID", 'Gene Name', 'Distance to TSS', 'Nearest PromoterID']]
annot["Distance to TSS"] = annot["Distance to TSS"].apply(lambda x: np.abs(x))
print(annot.shape)
annot = annot[annot["Distance to TSS"] < 2000]
print(annot.shape)

df = pd.merge(annot, peak, left_on="PeakID", right_on="PeakID") 
df2 = df.copy()
df2 = df2.rename(columns={"Gene Name": "Gene"})
df_mark_diff = df2[df2["Event"].isin(["Loss", "Gain"])]

df_meth_diff = pd.read_csv("NASH_vs_Ctrl_DMR_Filt_Modified_Genes.xls", sep="\t")
df_meth_diff = df_meth_diff[df_meth_diff["element"] == "promoter"]
df_rna = pd.read_csv("gene_TPM.xls", sep="\t")
df = pd.merge(df_meth_diff, df_mark_diff, left_on="GeneID", right_on="Gene")
df = pd.merge(df, df_rna, left_on="GeneID", right_on="GeneID")
df = df[["Event", "variation", "Ctrl1", "Ctrl2", "Ctrl3", "NASH1", "NASH2", "NASH3"]]
df = df.melt(id_vars=['Event', 'variation'], var_name='Sample', value_name='Value')

df_group = pd.DataFrame({"NASH": ["NASH1", "NASH2", "NASH3"], "CTRL": ["Ctrl1", "Ctrl2", "Ctrl3"]}).melt(var_name="Group", value_name="Sample")
df = pd.merge(df, df_group, left_on="Sample", right_on="Sample")
df["comb"] = df["Event"] + "-" + df["variation"]
df = df[["comb", "Group", "Value"]]
df.to_csv(f"{mark}.multi.txt", sep="\t", index=False)
